name: Deploy Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v7
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm run test
  build:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v7
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Server data
        run: |
          echo ">>>>>>>>"
          pwd
          whoami
          ls -la
          echo "<<<<<<<<"
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-files
          path: dist
          compression-level: '6'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v8
        with:
          name: dist-files
      - name: Server data
        run: |
          echo ">>>>>>>>"
          pwd
          whoami
          ls -la
          echo "<<<<<<<<"
      - name: Deploy
        run: echo "Deployment......MAIN........"
