name: Deploy Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v7
      - name: Cache dependencies
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm run test
  build:
    needs: lint_and_test
    runs-on: ubuntu-latest
    outputs:
      js-runfile: ${{ steps.publ.outputs.data }}
    steps:
      - name: Get code
        uses: actions/checkout@v7
      - name: Cache dependencies
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Server data
        run: |
          echo ">>>>>>>>"
          pwd
          whoami
          ls -la
          echo "<<<<<<<<"
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-files
          path: dist
      - name: Publish JS filename
        id: publ
        run: find dist/assets -type f -name "*.js" -execdir echo 'data={}' >> $GITHUB_OUTPUT ';'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v8
        with:
          name: dist-files
      - name: Server data
        run: |
          echo ">>>>>>>>"
          pwd
          whoami
          ls -la
          echo "<<<<<<<<"
      - name: Output filename
        run: echo "${{ needs.build.outputs.js-runfile }}"
      - name: Deploy
        run: echo "Deployment......MAIN........"
